[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/altonen/emissary"
readme = "README.md"
authors = []
keywords = []
categories = []

[workspace]
resolver = "2"

members = [
  "base",
  "node",
]

default-members = ["node"]

[workspace.dependencies]
