[package]
name = "emissary-util"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
emissary-core = { path = "../emissary-core", features = ["std"] }
flate2 = "1.0.33"
metrics = "0.23.0"
metrics-exporter-prometheus = "0.15.3"

# workspace dependencies
futures = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }
thingbuf = { version = "0.1.6", features = ["default"] }
tokio-util = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, features = ["log"] }

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:tokio-util"]
