[package]
name = "emissary-cli"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
emissary-core = { path = "../emissary-core", features = ["std"] }
flate2 = "1.0.33"
futures = "0.3.30"
home = "0.5.9"
metrics = "0.23.0"
metrics-exporter-prometheus = "0.15.3"
nom = "6.1.2"
rand = "0.8.5"
rand_core = { version = "0.6.4", default-features = false }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
tokio-util = { version = "0.7.11", features = ["compat"] }
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
tracing-subscriber = { version = "0.3.18", features = ["chrono", "env-filter", "time"] }
tracing = { version = "0.1.40", features = ["log"] }
x25519-dalek = { version = "2.0.1", features = ["getrandom", "static_secrets"] }
zip = { version = "2.1.3", features = ["deflate-zlib-ng"], default-features = false }

[dev-dependencies]
tempfile = "3.10.1"
