[[routers]]
type = "emissary"
log = "-lemissary=trace,emissary::subsystem=off"
count = 1

[[routers]]
type = "i2pd"
log = "debug"
count = 1

# [[routers]]
# name = "emissary-floodfill-1"
# type = "emissary"
# log = "-lemissary=trace,emissary::subsystem=off"

[[routers]]
name = "i2pd-floodfill-1"
type = "i2pd"
log = "debug"
floodfill = true
